Constant_3DEBuyer = 'Buyer'
Constant_Company_Info = 'Company Info'
Constant_Buyer_Info = 'Buyer Info'
Constant_Buyer_OrderNo = "Buyer's Order No."
Constant_Despatch_DocumentNo = "Despatch Document No."
Constant_Despatched_Through = "Despatched through"
Constant_Destination = "Destination"
Constant_TermsOfDelivery = "Terms Of Delivery"
Constant_Description = 'Description of Goods'
Constant_Items= "Items"
Constant_cid299 = '(cid:299)'
Constant_u2122  ='\u2122'
Constant_SL_No = "Sl No."
Constant_Sl = "Sl"
Constant_Description = "Description"
Constant_Amount_ChargeableInWords ="Amount Chargeable (in words)"
Constant_Amount_Chargeable ="Amount Chargeable"
Constant_Tax_Amount_words = "Tax Amount (in words)"
Constant_Authorised_Signatory = "Authorised Signatory"
Constant_HSN_SAC = "HSN/SAC"
Constant_Declaration = "Declaration for"
Constant_Tax_value = "Taxable Value"
Constant_Integrated_tax = "Integrated Tax"
Constant_Total_tax_amt = "Total Tax Amount"
Constant_BankName = "Bank Name"
Constant_Branch_IFS = "Branch & IFS Code"
COnstant_Account_no = "A/c No."
Constant_Declaration = "Declaration"
Constant_Invoice_No = "Invoice No"
Constant_Dated = "Dated"
Constant_Delivery_Note = "Delivery Note"
Constant_Delivery_NoteDate = "Delivery Note Date"
Constant_ModeTerms_Of_Payment= "Mode/Terms of Payment"
Constant_Suppliers_Ref= "Supplier’s Ref."
Constant_Other_Reference= "Other Reference(s)"
Constant_CGST= "cgst"
Constant_SGST= "sgst"
Constant_IGST= "IGST"
Constant_Tables= 'tables'
Constant_Buyer= "Buyer"
Constant_Type= "Type"
Constant_Rupees= "Rupees"
Constant_Invoice_Value= "INVOICE VALUE"
Constant_Rate= "Rate"
Constant_Amount= "Amount"
Constant_Total= "Total"
Constant_Items= "Items"
Constant_Taxes= "Taxes"

Constant_TotalAmount= "Total Amount"
Constant_DescriptionVaco = 'Description'
Constant_IndianRupees = 'Indian Rupees'
Constant_BankACNo = 'Bank A/c No.'
Constant_IFS_Code= 'IFS Code'
Constant_Branch_IFS_Code= 'Branch & IFS Code'
Constant_Amount_EOE="Amount Chargeable (in words) E. & O.E"


Constant_Company_SB = "Company Info"
Constant_Invoice = "Invoice No"
Constant_SBTech_Date="Date"
Constant_SBTech_OurDCNo="Our DC No."
Constant_SBTech_OurDCDate="Our Dc Date"
Constant_SBTech_YourDCNo="Your DC No."
Constant_SBTech_YourDCDate="Your DC Date"
Constant_SBTech_YourPONo="Your P.O. No."
Constant_SBTech_YourPODate="Your P.O. Date."
Constant_SBTech_Consignee="Consignee GST"
Constant_SBTech_Payment_Terms="Payment Terms"
Constant_SBTech_Mode_Terms_Payment="Mode/Terms of Payment"
Constant_SBTech_Supplier_Ref="Supplier’s Ref."
Constant_SBTech_Other_Ref="Other Reference(s)"
Constant_SBTech_Amount_Chargeable="Amount Chargeable (in words)"
Constant_SBTech_Auth_Sign="Authorised Signatory"
Constant_SBTech_Total_Amt="Total Amount"